### ISSUE TITLE
XmlReader.read causes CoderMalfunctionError: java.lang.NullPointerException

### ISSUE THREAD

**Issue by kriegaex** [codehaus-plexus/plexus-utils#193]
In the context of Maven Invoker integration tests for AspectJ Maven Plugin, I sometimes see GitHub CI builds fail. The problem never occurs locally on my Windows box. I run the build on combinations of Java version, OS and JVM flavour, 3 * 3 * 3 = 27 variants. Usually, it is just 1 of 27 builds failing, AFAIR Java 17 with OpenJ9 JVM. I cannot remember if it happens on several OS platforms, but the example I have for you happens to be Windows:

https://github.com/dev-aspectj/aspectj-maven-plugin/runs/5773643690?check_suite_focus=true#step:6:265

This is build run 1, if you scoll to the top of the page and select build run 2 of the exact same build, it passes. It is always like that, and it only happens sometimes. So it is not easily reproducible. The interesting thing is that in whichever integration test it happens first, that causes all subsequent ITs to fail, too. It can be the 5th or the last in a few dozen tests and seems to be random. Because Invoker starts a fresh Maven build for each IT, I am wondering how a problem in one IT can bleed over into the next one.

So now what is the problem about? I am not sure, but it seems as if somehow `XmlReader` is trying to guess the character set of a file (all my files are UTF-8), guesses ISO-8859-1 and subsequently something goes wrong (exception in build log starts [here](https://github.com/dev-aspectj/aspectj-maven-plugin/runs/5773643690?check_suite_focus=true#step:6:823):

```text
Error: Exception in thread "main" java.nio.charset.CoderMalfunctionError: java.lang.NullPointerException
	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:587)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:305)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at org.codehaus.plexus.util.xml.XmlReader.read(XmlReader.java:421)
	at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:3680)
	at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3776)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1717)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1700)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1319)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3876)
	at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:112)
	at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:85)
	at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:111)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:622)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1196)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:916)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:361)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:267)
...
Caused by: java.lang.NullPointerException
	at java.base/sun.nio.cs.ISO_8859_1$Decoder.decodeArrayLoop(ISO_8859_1.java:89)
	at java.base/sun.nio.cs.ISO_8859_1$Decoder.decodeLoop(ISO_8859_1.java:122)
	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:585)
```

Even though AspectJ.dev AspectJ Maven Plugin uses Plexus Utils 3.4.1, it seems as if Maven 3.8.5 itself uses 3.3.0 (see [build log](https://github.com/dev-aspectj/aspectj-maven-plugin/runs/5773643690?check_suite_focus=true#step:6:817)). But the few commits in `XmlReader` since 3.3.0 were cosmetic in nature, see [diff](https://github.com/codehaus-plexus/plexus-utils/compare/plexus-utils-3.3.0..plexus-utils-3.4.1#diff-007299e4e1fb2d0734ae9f1021b83fb688dc409835d0c6da59b2490d22443972). So my guess it that whetever the problem is, it has been there for a long time.

I have no idea how to even begin to debug this, given the fact that it only happens on GitHub and only occasionally. I hope that the debug build logs from the failed ITs help you to analyse the situation.

Are there any settings I can use other than the already existing

```xml
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
```

in both the plugin itself and in each IT's POM, in order to tell Plexus Utils not to try to be smart but simly assume UTF-8?

---

**Update:** Just to be sure, I compared the source code files for the involved JDK classes `CharsetDecoder`, `StreamDecoder`, `InputStreamReader` and `ISO_8859_1` between Oracle JDK 17 and OpenJ9 JDK 17. They are completely identical, except for copyright headers on top of each file. So there are differences in the JVMs between those two JDKs (Hotspot vs. OpenJ9), but no differences in Java code. I just wanted to be sure.

**Comment by kriegaex** [comment]
[Another build](https://github.com/dev-aspectj/aspectj-maven-plugin/runs/5836316512?check_suite_focus=true#step:6:9020) has failed, again Windows, Java 17, OpenJ9 VM. I am attaching the link, because build logs expire on GitHub after a while, and I am hoping that someone is going to read this before that happens.

**Comment by kriegaex** [comment]
I think that together with some OpenJ9 people we have [narrowed down the issue to a JIT compiler problem](https://github.com/eclipse-openj9/openj9/issues/14654#issuecomment-1094186716). So Plexus is out of the equation, as far as I can say presently. Sorry for the noise, but I had to start asking for help somewhere, and I started where the stack trace said the problem occurred.
