### ISSUE TITLE
NullPointerException in MXParser

### ISSUE THREAD

**Issue by rohanpadhye** [codehaus-plexus/plexus-utils#34]
Found this bug when testing Maven:
```
echo -n "<Y" > npe.xml  # File contains only '<Y' without newlines
mvn -f npe.xml
```

When using Maven 3.5.2 / plexus-utils 3.1.0, this throws an internal error:

```
Caused by: java.lang.NullPointerException
	at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:3054)
	at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3080)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseStartTag(MXParser.java:1776)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1517)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1436)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
	at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4399)
	at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:598)
```

Test case was generated automatically by [JQF](https://github.com/rohanpadhye/jqf)

**Comment by michael-o** [comment]
Very interesting case, thx.
